"""Durable session deadlines generated by a real MySQL database clock."""
from __future__ import annotations

from decimal import Decimal
from pathlib import Path
from uuid import uuid4

import pytest
from sqlalchemy import text

from app.core.redis_client import SESSION_TTL
from app.db import SessionLocal
from app.models import WecomInboundEvent
from app.services.conversation_service import StagedSessionCommit
from app.services.worker import Worker


pytestmark = pytest.mark.integration


def _apply_deadline_migration(db) -> None:
    path = (
        Path(__file__).resolve().parents[2]
        / "sql/migrations/phase10_003_session_commit_deadline.sql"
    )
    for statement in path.read_text(encoding="utf-8").split(";"):
        if statement.strip():
            db.execute(text(statement))
    db.commit()


def test_migration_backfills_existing_pending_and_is_idempotent():
    db = SessionLocal()
    row = WecomInboundEvent(
        msg_id=f"deadline-backfill-{uuid4()}",
        from_userid="integration-deadline-backfill",
        msg_type="text",
        content_brief="deadline backfill",
        status="session_pending",
        session_operation="delete",
        session_expected_version=0,
        session_payload={},
        session_commit_deadline_epoch=None,
    )
    event_id = None
    try:
        db.add(row)
        db.commit()
        event_id = int(row.id)

        _apply_deadline_migration(db)
        _apply_deadline_migration(db)
        db.expire_all()
        deadline = db.get(WecomInboundEvent, event_id).session_commit_deadline_epoch
        assert isinstance(deadline, Decimal)

        worker = object.__new__(Worker)
        claimed = worker._claim_session_commits(
            inbound_event_id=event_id,
            limit=1,
        )
        assert len(claimed) == 1
        assert claimed[0]["commit"].deadline_epoch == deadline
    finally:
        db.rollback()
        if event_id is not None:
            db.query(WecomInboundEvent).filter(
                WecomInboundEvent.id == event_id,
            ).delete(synchronize_session=False)
            db.commit()
        db.close()


def test_session_commit_deadline_schema_and_database_clock_generation():
    db = SessionLocal()
    event_id = None
    row = WecomInboundEvent(
        msg_id=f"deadline-{uuid4()}",
        from_userid="integration-deadline-user",
        msg_type="text",
        content_brief="deadline",
        status="processing",
    )
    try:
        column = db.execute(text(
            "SELECT column_type, is_nullable "
            "FROM information_schema.columns "
            "WHERE table_schema=DATABASE() "
            "AND table_name='wecom_inbound_event' "
            "AND column_name='session_commit_deadline_epoch'"
        )).one()
        assert column[0] == "decimal(20,6)"
        assert column[1] == "YES"

        db.add(row)
        db.flush()
        event_id = int(row.id)
        worker = object.__new__(Worker)
        worker._stage_session_commit(
            db,
            row.id,
            StagedSessionCommit(
                userid=row.from_userid,
                operation="delete",
                expected_version=0,
                payload=None,
            ),
        )
        db.flush()

        deadline, remaining = db.execute(text(
            "SELECT session_commit_deadline_epoch, "
            "session_commit_deadline_epoch - UNIX_TIMESTAMP(NOW(6)) "
            "FROM wecom_inbound_event WHERE id=:event_id"
        ), {"event_id": row.id}).one()
        assert isinstance(deadline, Decimal)
        assert Decimal(SESSION_TTL - 1) <= remaining <= Decimal(SESSION_TTL)
        row.session_payload = {}
        db.commit()

        claimed = worker._claim_session_commits(
            inbound_event_id=event_id,
            limit=1,
        )
        assert len(claimed) == 1
        assert claimed[0]["commit"].deadline_epoch == deadline
    finally:
        db.rollback()
        if event_id is not None:
            db.query(WecomInboundEvent).filter(
                WecomInboundEvent.id == event_id,
            ).delete(synchronize_session=False)
            db.commit()
        db.close()
