-- Add an absolute database-clock deadline for durable Redis session commits.
-- Stop all old workers before applying this migration because mixed workers can stage
-- new NULL deadlines after the backfill. Safe to apply repeatedly on MySQL 8.0.

SET @schema_name = DATABASE();

SET @ddl = IF(
    EXISTS(
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = @schema_name
          AND table_name = 'wecom_inbound_event'
          AND column_name = 'session_commit_deadline_epoch'
    ),
    'SELECT 1',
    'ALTER TABLE `wecom_inbound_event`
       ADD COLUMN `session_commit_deadline_epoch` DECIMAL(20,6) NULL
       AFTER `session_next_attempt_at`'
);
PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- Existing pending work receives a conservative deadline based on timestamps
-- already generated by MySQL. Old work may therefore be immediately expired;
-- it must never receive a fresh TTL from migration time.
UPDATE `wecom_inbound_event`
   SET `session_commit_deadline_epoch` = CAST(
       UNIX_TIMESTAMP(COALESCE(`worker_started_at`, `created_at`)) + 1800
       AS DECIMAL(20,6)
   )
 WHERE `status` = 'session_pending'
   AND `session_commit_deadline_epoch` IS NULL;
