-- Frozen Job DDL from the immutable Stage A schema deployed before Phase 10.
CREATE TABLE `job` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `owner_userid` VARCHAR(64) NOT NULL,
  `city` VARCHAR(32) NOT NULL,
  `job_category` VARCHAR(32) NOT NULL,
  `salary_floor_monthly` INT NOT NULL,
  `pay_type` ENUM('月薪','时薪','计件') NOT NULL,
  `headcount` INT NOT NULL,
  `gender_required` ENUM('男','女','不限') NOT NULL DEFAULT '不限',
  `age_min` TINYINT UNSIGNED DEFAULT NULL,
  `age_max` TINYINT UNSIGNED DEFAULT NULL,
  `is_long_term` TINYINT(1) NOT NULL DEFAULT 1,
  `district` VARCHAR(32) DEFAULT NULL,
  `address` VARCHAR(255) DEFAULT NULL,
  `salary_ceiling_monthly` INT DEFAULT NULL,
  `provide_meal` TINYINT(1) DEFAULT NULL,
  `provide_housing` TINYINT(1) DEFAULT NULL,
  `dorm_condition` VARCHAR(255) DEFAULT NULL,
  `shift_pattern` VARCHAR(128) DEFAULT NULL,
  `work_hours` VARCHAR(128) DEFAULT NULL,
  `accept_couple` TINYINT(1) DEFAULT NULL,
  `accept_student` TINYINT(1) DEFAULT NULL,
  `accept_minority` TINYINT(1) DEFAULT NULL,
  `height_required` VARCHAR(32) DEFAULT NULL,
  `experience_required` VARCHAR(255) DEFAULT NULL,
  `education_required` ENUM('不限','初中','高中','中专','大专及以上') DEFAULT '不限',
  `rebate` VARCHAR(255) DEFAULT NULL,
  `employment_type` ENUM('厂家直招','劳务派遣','中介代招') DEFAULT NULL,
  `contract_type` ENUM('长期合同','短期合同','劳务关系') DEFAULT NULL,
  `min_duration` VARCHAR(64) DEFAULT NULL,
  `job_sub_category` VARCHAR(64) DEFAULT NULL,
  `raw_text` TEXT NOT NULL,
  `description` TEXT DEFAULT NULL,
  `images` JSON DEFAULT NULL,
  `miniprogram_url` VARCHAR(512) DEFAULT NULL,
  `audit_status` ENUM('pending','passed','rejected') NOT NULL DEFAULT 'pending',
  `audit_reason` VARCHAR(255) DEFAULT NULL,
  `audited_by` VARCHAR(64) DEFAULT NULL,
  `audited_at` DATETIME DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `expires_at` DATETIME NOT NULL,
  `delist_reason` ENUM('filled','manual_delist','expired') DEFAULT NULL,
  `deleted_at` DATETIME DEFAULT NULL,
  `version` INT UNSIGNED NOT NULL DEFAULT 1,
  `extra` JSON DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_owner` (`owner_userid`),
  KEY `idx_audit_time` (`audit_status`, `created_at`),
  KEY `idx_expires` (`expires_at`),
  KEY `idx_filter_hot` (`city`, `job_category`, `is_long_term`, `audit_status`, `deleted_at`, `expires_at`),
  KEY `idx_salary` (`salary_floor_monthly`),
  CONSTRAINT `fk_job_owner` FOREIGN KEY (`owner_userid`)
    REFERENCES `user` (`external_userid`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='岗位信息表';
